# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bs_db_connector_msg/db_connector.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from default_msg import default_pb2 as default__msg_dot_default__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&bs_db_connector_msg/db_connector.proto\x1a\x19\x64\x65\x66\x61ult_msg/default.proto\"\x19\n\x06UserId\x12\x0f\n\x07user_id\x18\x01 \x01(\t\",\n\tLoginData\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"0\n\x0b\x42\x61lanceInfo\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x02\x12\x10\n\x08\x63urrency\x18\x02 \x01(\t\"s\n\x08UserInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x14\n\x0cphone_number\x18\x04 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x05 \x01(\t\x12\r\n\x05login\x18\x06 \x01(\t2|\n\x12\x44\x62\x43onnectorService\x12#\n\nGetBalance\x12\x07.UserId\x1a\x0c.BalanceInfo\x12!\n\x0bGetUserInfo\x12\x07.UserId\x1a\t.UserInfo\x12\x1e\n\x05Login\x12\n.LoginData\x1a\t.UserInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bs_db_connector_msg.db_connector_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERID._serialized_start=69
  _USERID._serialized_end=94
  _LOGINDATA._serialized_start=96
  _LOGINDATA._serialized_end=140
  _BALANCEINFO._serialized_start=142
  _BALANCEINFO._serialized_end=190
  _USERINFO._serialized_start=192
  _USERINFO._serialized_end=307
  _DBCONNECTORSERVICE._serialized_start=309
  _DBCONNECTORSERVICE._serialized_end=433
# @@protoc_insertion_point(module_scope)
