# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bs_authentication_msg/authentication.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from default_msg import default_pb2 as default__msg_dot_default__pb2
from bs_db_connector_msg import db_connector_pb2 as bs__db__connector__msg_dot_db__connector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*bs_authentication_msg/authentication.proto\x1a\x19\x64\x65\x66\x61ult_msg/default.proto\x1a&bs_db_connector_msg/db_connector.proto27\n\x15\x41uthenticationService\x12\x1e\n\x05Login\x12\n.LoginData\x1a\t.UserInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bs_authentication_msg.authentication_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUTHENTICATIONSERVICE._serialized_start=113
  _AUTHENTICATIONSERVICE._serialized_end=168
# @@protoc_insertion_point(module_scope)
